# Generated by Django 4.1.7 on 2023-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='background_image',
        ),
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='bg_img'),
        ),
    ]
