# Generated by Django 4.1.7 on 2023-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_carousel_background_image_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='bg_img/'),
        ),
    ]
